import type { Metadata } from "next";
import "./globals.css";
import MainPage from "./pages/main/main-page";

export const metadata: Metadata = {
  title: "Marcin's SPA",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en" >
      <body>
        <MainPage />
      </body>
    </html>
  );
}
